### ISSUE TITLE
Feature request: installation wizard

### ISSUE THREAD

**Issue by techge** [vletoux/OpenPGP-CSP#3]
Until now one have to copy the binary by hand and change registries accordingly.
A simple installation wizard would be great instead. :)

**Comment by vletoux** [comment]
Done in b117a07b83b04ea956786b0b21c7877ca132e492 and release published

**Comment by alex-nitrokey** [comment]
Hi Vincent,

thanks for your effort! Could you please either make the installer workable for both, 32 and 64 bit (don't know how it is on WIndows) or add a 64bit compatible version?

![screenshot_20180525_100434](https://user-images.githubusercontent.com/36155797/40533418-088ef846-6003-11e8-9410-077cb9771a72.png)

**Comment by vletoux** [comment]
Indeed I uploaded only the x86 installer

Regards
Vincent

**Comment by alex-nitrokey** [comment]
So do you plan to add 64bit later? Do you have an ETA?

**Comment by vletoux** [comment]
Tonight / tomorrow

**Comment by alex-nitrokey** [comment]
Thanks! No hurry, won't get to it before Monday.

**Comment by vletoux** [comment]
release updated
