### ISSUE TITLE
Creating cert key for CA: PIN request window in background

### ISSUE THREAD

**Issue by techge** [vletoux/OpenPGP-CSP#4]
When trying to create a root certificate on OpenPGP Card (signature slot) for a AD CS , the windows for admin PIN request opens *behind* the creation wizard window and is likely to be overseen. This results in cancellation of process eventually.

**Comment by vletoux** [comment]
fixed in 56b45626dfaaf558e9fc9c7d4ef2bd8c97af2223

**Comment by alex-nitrokey** [comment]
Looks good, thanks!
