### ISSUE TITLE
Moving project to free-of-cost community editions of VS

### ISSUE THREAD

**Issue by alex-nitrokey** [vletoux/OpenPGP-CSP#7]
It would be marvellous if the project would not depend on older VS versions which interested developer might need to buy to improve the code or add functions.

When trying to transform the project to VS IDE 2017 Community I run into several lib problems. I know too less about VS and windows programming myself, unfortunately...

**Comment by vletoux** [comment]
see 57bf8379dc73166ee46241c219652b0503696137

**Comment by alex-nitrokey** [comment]
Thanks, looks good!

I just realized that when building the solution one has to build it twice, one time with x64 enabled (default) and a second time with x86 enabled (manually configured by me), because the installer needs both files of course. 

Can you automate the building of both arch, so that building the solution works at once? Sorry that I am quite ignorant about those minor issues. I don't know how easily contributors would get that...

**Comment by vletoux** [comment]
Msbuild script
But with hard coded paths, it is simpler to compile x86 then x64

Given my experience you need a kernel mode code signing certificate and it is already above the average developper level

**Comment by alex-nitrokey** [comment]
> Given my experience you need a kernel mode code signing certificate and it is already above the average developper level

Fair enough...
